apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alpha-office-rest
  labels:
    commit: 757251661826bd1ae15e3195e0f0df7869383b41
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alpha-office-rest
  template:
    metadata:
      labels:
        app: alpha-office-rest
        commit: 757251661826bd1ae15e3195e0f0df7869383b41
    spec:
      containers:
      - name: alpha-office-rest-container
        image: wcr.io/derekoneil/alpha-office-rest:wercker-757251661826bd1ae15e3195e0f0df7869383b41
        imagePullPolicy: Always
        ports:
        - name: ao-rest-port
          containerPort: 8080
          protocol: TCP
      imagePullSecrets:
        - name: wercker
---
apiVersion: v1
kind: Service
metadata:
  name: alpha-office-rest-service
  labels:
    app: alpha-office-rest
    commit: 757251661826bd1ae15e3195e0f0df7869383b41
spec:
  ports:
  - port: 30000
    targetPort: 8080
  selector:
    app: alpha-office-rest
    commit: 757251661826bd1ae15e3195e0f0df7869383b41
  type: LoadBalancer
---
