apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: product-catalog-ui
  labels:
    commit: 9aa32a20b29ba7dba7480400ba2b3efa7281c787
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-catalog-ui
  template:
    metadata:
      labels:
        app: product-catalog-ui
        commit: 9aa32a20b29ba7dba7480400ba2b3efa7281c787
    spec:
      containers:
      - name: product-catalog-ui-container
        image: wcr.io/derekoneil/product-catalog-ui:kubernetes-cicd-9aa32a20b29ba7dba7480400ba2b3efa7281c787
        imagePullPolicy: Always
        ports:
        - name: pc-ui-port
          containerPort: 80
          protocol: TCP
      imagePullSecrets:
        - name: wercker
---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog-ui-service
  labels:
    app: product-catalog-ui
    commit: 9aa32a20b29ba7dba7480400ba2b3efa7281c787
spec:
  ports:
  - port: 30000
    targetPort: 80
  selector:
    app: product-catalog-ui
    commit: 9aa32a20b29ba7dba7480400ba2b3efa7281c787
  type: LoadBalancer
---
